=== kent-gsi/kent-eliott-example/DTD/letters.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--                                                   -->
<!-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv -->
<!-- Project: T.S. Eliot as a Family Man               -->
<!-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv -->
<!--                                                   -->
<!-- Project lead: (anonymised for assessment)         -->
<!-- with the guidance of Dr Simon Mahony              -->
<!--                                                   -->
<!-- part of INSTG037, MSc in DH, 2017/18.             -->
<!--                                                   -->
<!-- filename:                                         -->
<!--     letters.dtd                                   -->
<!--                                                   -->
<!-- description:                                      -->
<!--     setting up the DTD for letters.xml            -->
<!--     used to generate each <letter>                -->
<!--                                                   -->
<!-- convention:                                       -->
<!--     I generally favor readability over concision  -->
<!--     hence e.g. source/source-archive-id           -->
<!--                rather than source/archive-id      -->
<!--                                                   -->
<!-- arbitrary conventions:                            -->
<!--     For some reason I don't like the spaces       -->
<!--      before > automatically generated by Oxygen   -->
<!--      Ergo I got rid all of them                   -->
<!--     But I love spaces surrounding | :)            -->
<!--                                                   -->
<!-- reminder:                                         -->
<!--     Some elements like notes and page breaks can  -->
<!--     be anywhere, so think twice when you have     -->
<!--     only (#PCDATA) for an element definition.     -->
<!-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv -->
<!--                                                   -->

<!-- SOME TO-DO/TO-THINK                               -->

<!-- To do: use parameter entities to split this (growing) dtd up -->
<!-- <!ENTITY % info SYSTEM "import/info.dtd"> -->

<!-- It's possible to use entity to separate long body texts from letters.xml -->
<!-- might consider taking advantage of it in the future so we won't end up   -->
<!-- having a gigantic letter.xml - although now Oxygen can collapse things   -->
<!-- very easily.                                                             -->
<!-- <!ENTITY letter-1-text SYSTEM "../XML/import/letter-1-text.xml"> -->

<!-- STARTS HERE                                      -->

<!-- root element -->
<!ELEMENT letters (letter+)> 

<!-- defining document strucutre: individual letter -->
<!ELEMENT letter (info, body)>
<!ATTLIST letter id CDATA #REQUIRED
                 language CDATA #REQUIRED>

<!-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv -->
<!-- defining major document strucutre: letter/info -->
<!-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv -->
<!ELEMENT info (tse-age, output-title-prefix, recipient, date, source, address)>

<!ELEMENT tse-age (#PCDATA)>
<!ELEMENT output-title-prefix (#PCDATA)>

<!ELEMENT recipient (#PCDATA | note)*>
<!ATTLIST recipient recipient-id CDATA #REQUIRED>

<!-- Some letters have dates that look like:  -->
<!-- [Recieved 17 April 1924]  -->
<!ELEMENT date (#PCDATA | year| month | day)*>
<!ATTLIST date type CDATA #IMPLIED>
<!ELEMENT year (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT day (#PCDATA)>

<!ELEMENT source (source-archive-id, source-archive-status, source-archive-name, source-book-id, source-book-title, source-book-page-no)>
<!ELEMENT source-archive-id (#PCDATA)>
<!ELEMENT source-archive-status (#PCDATA)>
<!ELEMENT source-archive-name (#PCDATA)>
<!ELEMENT source-book-id (#PCDATA)>
<!ELEMENT source-book-title (#PCDATA | title)*>
<!ELEMENT source-book-page-no (source-book-page-no-start, source-book-page-no-end)>
<!ELEMENT source-book-page-no-start (#PCDATA)>
<!ELEMENT source-book-page-no-end (#PCDATA)>

<!-- Many addresses are supplied by the editor of my source material,            -->
<!-- and they can be complete ones including street number and postcode etc.     -->
<!-- or rather vague ones like [London], hence the type definitions that follow. -->
<!ELEMENT address (#PCDATA | address-line | town | city | postcode | title)*>
<!ATTLIST address type CDATA #IMPLIED>
<!ELEMENT address-line (#PCDATA)>
<!ELEMENT town (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>



<!-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv -->
<!-- defining major document strucutre: letter/body -->
<!-- xxxxxxxxxxxxxxxxxxxxxvvvvvvvxxxxxxxxxxxxxxxxxxx -->

<!ELEMENT body (greeting | para | table | quote | closer | note | postscript | page-break)*>

<!ELEMENT greeting (greeting-text, greeting-name, greeting-punct*)>
<!ELEMENT greeting-text (#PCDATA)>
<!ELEMENT greeting-name (#PCDATA)>
<!ELEMENT greeting-punct (#PCDATA)>

<!ELEMENT para (#PCDATA | quote | list | table | link | note | emphasis | title | page-break)*>
<!ATTLIST para first CDATA #IMPLIED 
               last CDATA #IMPLIED>

<!ELEMENT quote (#PCDATA | quote | person-name | place-name | list | table | link | note | emphasis | title | page-break)*>
<!ATTLIST quote type CDATA #REQUIRED>

<!ELEMENT person-name (#PCDATA)>
<!ELEMENT place-name (#PCDATA)>

<!ELEMENT closer (#PCDATA | closer-text | closer-name)*>
<!ELEMENT closer-text (#PCDATA | link | note)*>
<!ELEMENT closer-name (#PCDATA | link | note)*>

<!ELEMENT postscript (#PCDATA | quote | list | table | link | note | emphasis | title | page-break)*>

<!-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv -->
<!-- defining commonly used elements -->
<!-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv -->


<!ELEMENT note (#PCDATA | link | title | emphasis | page-break)*>
<!ATTLIST note n CDATA #REQUIRED
               type CDATA #IMPLIED>

<!ELEMENT table (row+)>
<!ELEMENT row (column+)>
<!ELEMENT column (#PCDATA | link | note | emphasis | title | page-break)*>

<!ELEMENT list (item+)>
<!ATTLIST list type CDATA #REQUIRED>
<!ELEMENT item (#PCDATA | link | note | emphasis | title | page-break)*>



<!-- Those can be everywhere -->

<!ELEMENT link (#PCDATA)>
<!ATTLIST link to CDATA #REQUIRED>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title type CDATA #IMPLIED>

<!ELEMENT emphasis (#PCDATA)>

<!ELEMENT page-break EMPTY>
<!ATTLIST page-break pn CDATA #REQUIRED>

=== kent-gsi/kent-eliott-example/XML/letter-temp.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XSL/letter.xsl"?>
<!-- <!DOCTYPE letters SYSTEM "../DTD/letters.dtd"> -->

<!--                                                                                             -->
<!-- Project: T.S. Eliot as a Family Man                               -->
<!--                                                                                             -->
<!-- filename: letters.xml                                                        -->
<!-- description:                                                                       -->
<!--     store the information for individual lettters             -->
<!--      indivudal letter body texts in                                     -->
<!--             /individual-letter-body                                         -->
<!--                                                                                             -->
<!--      associated .dtd: ../DTD/letter.dtd                             -->
<!--                                                                                             -->
<letters>
    <letter id="1" language="English">
        <info>
            <tse-age>34</tse-age>
            <output-title-prefix>To </output-title-prefix>
            <recipient id='recipient-1'>
                Henry Eliot
                <note n="1">Henry Eliot: see
                    &lt;a href="glossary-of-names.html"&gt; Glossary of Names &lt;/a&gt;.
                </note>
            </recipient>
            <date>
                <year>1923</year>
                <month>January</month>
                <day>2</day>
            </date>
            <source>
                <source-archive-id>1</source-archive-id>
                <source-archive-status>TS</source-archive-status>
                <source-archive-name>Houghton</source-archive-name>
                <source-book-id>1</source-book-id>
                <source-book-title>The Letters of T.S. Eliot: Volume 2: 1923–1925</source-book-title>
                <source-book-page-no>1–5</source-book-page-no>
            </source>
            <address type="full">
                <address-line>9 Clarence Gate Gdns</address-line>
                <city>London</city>
                <postcode>N.W.1</postcode>
            </address>
        </info>
        <body>
            <greeting>
                <greeting-text>My dear</greeting-text>
                <greeting-name>Henry</greeting-name>
                <greeting-punct>,</greeting-punct>
            </greeting>
            <para first="true">
                I have so much to write to you about that I must divide it into two or three letters. The three chief subjects are
                <list type="unnumbered">
                    <item>
						<note n="2" type="source-book">
							<note-target>Hydraulic</note-target>
                        	<note-content>
                            	The Hydraulic-Press Brick Company, established in St Louis in 1864. TSE’s father Henry Ware Eliot had been chairman of the company from 1909 until his death in 1919.</note>
							</note-content>
						</note>
					</item>
                        <item> the Bank </item>
                        <item> Mother’s visit </item>
                    </list>
            </para>
            <para>
                I will only deal in this letter with the latter two.
            </para>
            <para>
                <quote type="place"> Of course I must thank you for your goodness in writing so often, and keeping me posted about finance in <place-name>America</place-name>, and for your last admirable letter.</quote> And most of all for your latest extraordinary generosity. About your cheque: I imagine that you sent it under the impression that I had either just left the bank, or that <note n="3" type="source-book"> <note-target>I was just about to leave.</note-target> <note-content> TSE was considering leaving Lloyds Bank (where he had started work in the Colonial and Foreign Department in Mar. 1917), but did not ultimately do so until late 1925. </note-content></note> There are three reasons why I have not yet done so and cannot at the present time. But I feel that I ought to return it to you: I will either do that, or else invest it until needed, as you prefer. Please say. I do not want to take it under any misapprehension on your part. But if I invest it,<quote type="place"> I think I shall return it to you to invest for me in <place-name>America</place-name>, as I do not like sinking any more money in  <place-name>England </place-name> at the present juncture. </quote>
            </para>
            <para>
                I cannot possibly leave the bank at present, because of the way in which they have
                treated me. In spite of the fact that I have been absent about ten or eleven weeks
                during the past year, owing to Vivien’s illness, and constantly late, they have  raised my salary to five hundred pounds, at a time when they are raising very few salaries indeed. But this is not the main point. That is that they have shown me in  word and deed that they value my services very highly indeed, and have placed me in  a position of responsibility such that I cannot resign now without letting them down very badly and behaving with ingratitude. I am now head of an Intelligence    <page-break pn="2" /> Department with a number of clerks under me, and in sole charge. I have had to organise the department, and the organisation is still far from complete. On the contrary, they are just on the point of enlarging the scope of the department much more. The heads of the bank are anxious to make a big thing of it; and I know quite well that there is at present no one else in the bank but myself who can do it for them – that is, the one or two men who might do it are not available for this post. This is not a boast: it is simply the fact that there happens to be no one available with the proper qualifications, and as a matter of fact they had me in view from the inception of the idea. The bank is getting bigger and bigger, with interests practically all over the world, and affiliated banks everywhere, and there is the opportunity to create a service of Intelligence which would be quite unique. It has involved very heavy work so far: I have had to draft schemes, and at the same time attend to a mass of detail, such as the running of a printing press (which is always breaking down) and the holidays and attendances and personal grievances of the clerks; and although I have much more liberty of movement than before, I have had to be at the bank early and late to get the work done. And with it all I have to read ten or fifteen papers a day to try to keep myself posted on all sorts of subjects, such as foreign budgets, movements of crops, agricultural banks, oil developments, and what not. In addition, I am still unfortunately the only person in the bank who knows anything about the Peace Treaties, and there are two or three big lawsuits with Germans coming on this winter which involve an intimate knowledge of their history for the past four years, which no one else possesses. You will think that I have got excited about all this, but the fact remains that if I left the bank now I should simply be hanging another millstone round my conscience. The bank took me in without knowing anything about me whatever, when I was absolutely on the rocks in 1917, and has treated me with extraordinary kindness ever since. Of course this big expansion of the Intelligence work has only happened since my decision to leave: this summer I was merely running a daily newspaper of extracts from the foreign press, with another man, and it would not have been nearly so disconcerting for the bank if I had left then.
            </para>
            <para>
                This is my main reason. Another reason is the social uncertainty, <note n="1" type="source-book"> <note-target>owing to the
                alarming rise of the Labour Party to power.</note-target> <note-content> At the
